title: Home Sweet Home Docs
description: Documentation for HSH project
theme: just-the-docs
logo: "/assets/img/logo.png"

url: https://esposimo.github.io/hsh


heading_anchors: true


aux_links:
  GitHub Repository: https://github.com/esposimo/hsh
aux_links_new_tab: true



footer_content: "Copyright &copy; 2025 Simone Esposito"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

color_scheme: dark

nav_enabled: true
nav:
  - title: "Introduzione"
    url: "/scope.md"
    children:
      - title: "Scopo del progetto"
        url: "/scopo"

  - title: "Struttura del progetto"
    url: "/install"
    children:
      - title: "Tecnologie utilizzate"
        url: "/tecnologie"
      - title: "Struttura a più ambienti (dev, test, prod)"
        url: "/ambienti"

  - title: "Installazione"
    url: "/installazione"
    children:
      - title: "Prerequisiti"
        url: "/prerequisiti"
      - title: "Procedura di installazione passo passo"
        url: "/installazione-passo-passo"
      - title: "Configurazione Ambiente"
        url: "/configurazione-ambiente"

  - title: "Deployment"
    url: "/deployment"
    children:
      - title: "Come deployare una applicazione"
        url: "/come-deployare"
      - title: "Deploy Applicazione A"
        url: "/deploy-app-a"
      - title: "Deploy Applicazione B"
        url: "/deploy-app-b"
      - title: "Come aggiungere una applicazione ex novo"
        url: "/aggiungere-app"
      - title: "Struttura di una applicazione ex novo"
        url: "/struttura-app"

  - title: "Gestione dei servizi"
    url: "/servizi"
    children:
      - title: "Perché uso Consul?"
        url: "/perche-consul"
      - title: "Perché uso Vault?"
        url: "/perche-vault"
      - title: "Utilizzare il Consul di progetto per recuperare informazioni"
        url: "/usare-consul"
      - title: "Gestione dei secret"
        url: "/gestione-secret"
      - title: "Richiamare Terraform state di altro progetto"
        url: "/terraform-state-esterno"

  - title: "Script e automazioni"
    url: "/script"
    children:
      - title: "Cosa fanno gli script Bash"
        url: "/script-bash"

  - title: "Esporre servizi sul web"
    url: "/esporre"
    children:
      - title: "Esporre una applicazione sul web"
        url: "/esporre-app"
      - title: "Configurazione con Cloudflare"
        url: "/cloudflare"

# Impostazioni URL
baseurl: "/docs"  # se la documentazione è in /docs

