title: Home Sweet Home Docs
description: Documentation for HSH project
theme: just-the-docs

url: https://esposimo.github.io/hsh

nav_enabled: true

heading_anchors: true


aux_links:
  GitHub Repository: https://github.com/esposimo/hsh
aux_links_new_tab: true



footer_content: "Copyright &copy; 2025 Simone Esposito"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

color_scheme: dark
